FROM ghcr.io/dojoengine/dojo:v1.8.6
RUN apt-get update -qq && apt-get install -y -qq build-essential curl git pkg-config libssl-dev && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
ENV PATH="/root/.cargo/bin:${PATH}"
ENV SCARB=/opt/asdf/shims/scarb
WORKDIR /app
