#!/usr/bin/env bash
# Start the full local dev environment:
#   1. Katana (Starknet devnet)
#   2. Build & migrate contracts
#   3. Torii (indexer)
#
# Usage: ./scripts/local-dev.sh
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

echo "=== Siege Dojo Local Dev ==="
echo ""

# ── 1. Start Katana ──────────────────────────────────────────────
echo "[1/4] Starting Katana..."
docker compose up -d katana 2>&1 | grep -v "WORLD_ADDRESS"
echo "  Waiting for Katana to be ready..."
for i in $(seq 1 20); do
  if curl -s http://localhost:5050 > /dev/null 2>&1; then
    echo "  Katana ready on http://localhost:5050"
    break
  fi
  if [ "$i" -eq 20 ]; then
    echo "  ERROR: Katana failed to start. Check: docker compose logs katana"
    exit 1
  fi
  sleep 2
done

# ── 2. Build contracts ───────────────────────────────────────────
echo ""
echo "[2/4] Building contracts (this may take a few minutes on first run)..."
docker compose run --rm builder sozo build 2>&1 | tail -5

# ── 3. Migrate contracts ─────────────────────────────────────────
echo ""
echo "[3/4] Migrating contracts..."
MIGRATE_OUTPUT=$(docker compose run --rm builder \
  sozo migrate --rpc-url http://katana:5050 2>&1) || {
    echo "$MIGRATE_OUTPUT"
    echo ""
    echo "  ERROR: Migration failed."
    exit 1
  }
echo "$MIGRATE_OUTPUT" | grep -v "^time=" | tail -20

# Grant writer permissions (namespace-level) if migration didn't handle them
PERMS_SYNCED=$(echo "$MIGRATE_OUTPUT" | grep -oE 'Sync [0-9]+ permissions' | grep -oE '[0-9]+')
if [ "${PERMS_SYNCED:-0}" = "0" ]; then
  echo ""
  echo "  Granting writer permissions..."
  docker compose run --rm builder sozo auth grant writer \
    siege_dojo,siege_dojo-actions \
    siege_dojo,siege_dojo-commit_reveal \
    siege_dojo,siege_dojo-resolution \
    --rpc-url http://katana:5050 --wait 2>&1 | grep -v "^time=" | tail -3
fi

# Extract world address from "world at address 0x..."
WORLD_ADDRESS=$(echo "$MIGRATE_OUTPUT" | grep -oE 'address 0x[0-9a-fA-F]+' | grep -oE '0x[0-9a-fA-F]+' | head -1)

if [ -z "$WORLD_ADDRESS" ]; then
  echo ""
  echo "  WARNING: Could not auto-detect world address."
  echo "  Check the output above and run manually:"
  echo "    WORLD_ADDRESS=0x... docker compose up -d torii"
  exit 1
fi

echo ""
echo "  World address: $WORLD_ADDRESS"

# ── 4. Start Torii ───────────────────────────────────────────────
echo ""
echo "[4/4] Starting Torii..."
WORLD_ADDRESS="$WORLD_ADDRESS" docker compose up -d torii 2>&1 | grep -v "WORLD_ADDRESS"
sleep 3
echo "  Torii GraphQL: http://localhost:8080/graphql"

# ── Update frontend .env.local ───────────────────────────────────
echo ""
echo "  Updating frontend/.env.local..."

# Read contract addresses from manifest_dev.json (generated by sozo migrate)
MANIFEST="$PROJECT_DIR/manifest_dev.json"
if [ -f "$MANIFEST" ]; then
  ACTIONS_ADDR=$(python3 -c "
import json
with open('$MANIFEST') as f:
    m = json.load(f)
for c in m.get('contracts', []):
    if 'actions' in c.get('tag', ''):
        print('0x' + c['address'].lstrip('0x').zfill(66))
        break
" 2>/dev/null) || true

  COMMIT_ADDR=$(python3 -c "
import json
with open('$MANIFEST') as f:
    m = json.load(f)
for c in m.get('contracts', []):
    if 'commit_reveal' in c.get('tag', ''):
        print('0x' + c['address'].lstrip('0x').zfill(66))
        break
" 2>/dev/null) || true

  RESOLUTION_ADDR=$(python3 -c "
import json
with open('$MANIFEST') as f:
    m = json.load(f)
for c in m.get('contracts', []):
    if 'resolution' in c.get('tag', ''):
        print('0x' + c['address'].lstrip('0x').zfill(66))
        break
" 2>/dev/null) || true
fi

cat > frontend/.env.local <<EOF
NEXT_PUBLIC_RPC_URL=http://localhost:5050
NEXT_PUBLIC_WORLD_ADDRESS=${WORLD_ADDRESS}
NEXT_PUBLIC_ACTIONS_ADDRESS=${ACTIONS_ADDR:-UNKNOWN}
NEXT_PUBLIC_COMMIT_REVEAL_ADDRESS=${COMMIT_ADDR:-UNKNOWN}
NEXT_PUBLIC_RESOLUTION_ADDRESS=${RESOLUTION_ADDR:-UNKNOWN}
EOF

echo ""
echo "=== Done! ==="
echo ""
echo "  Katana:  http://localhost:5050"
echo "  Torii:   http://localhost:8080/graphql"
echo ""
echo "  To start the frontend:"
echo "    cd frontend && npm run dev"
echo ""
echo "  To stop everything:"
echo "    docker compose down"
